/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.rescuer;

import control.Consult;
import control.SysConexion;
import control.Validation;
import static java.lang.Integer.parseInt;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.FillComboBox;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author mauri
 */
public class RegisterRescuer extends javax.swing.JFrame {

    /**
     * Creates new form BlackList
     */
    FillComboBox filling = new FillComboBox();
    public RegisterRescuer() {
        initComponents();
        province.setVisible(false);
        okProvince.setVisible(false);
        LabelProvince.setVisible(false);
        canton.setVisible(false);
        okCanton.setVisible(false);
        LabelCanton.setVisible(false);
        district.setVisible(false);   
        LabelDistrict.setVisible(false);
        
        filling.FillCountry(country);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        SName = new javax.swing.JTextField();
        FSurname = new javax.swing.JTextField();
        SSurname = new javax.swing.JTextField();
        ced = new javax.swing.JTextField();
        canton = new javax.swing.JComboBox<>();
        country = new javax.swing.JComboBox<>();
        district = new javax.swing.JComboBox<>();
        province = new javax.swing.JComboBox<>();
        slider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelProvince = new javax.swing.JLabel();
        LabelCanton = new javax.swing.JLabel();
        LabelDistrict = new javax.swing.JLabel();
        labelFN = new javax.swing.JLabel();
        labelSN = new javax.swing.JLabel();
        labelFS = new javax.swing.JLabel();
        labelSS = new javax.swing.JLabel();
        tag1 = new javax.swing.JLabel();
        tag2 = new javax.swing.JLabel();
        tag3 = new javax.swing.JLabel();
        labelCed = new javax.swing.JLabel();
        YY = new javax.swing.JTextField();
        DD = new javax.swing.JTextField();
        MM = new javax.swing.JTextField();
        LabelDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LabelDD = new javax.swing.JLabel();
        LabelMM = new javax.swing.JLabel();
        LabelYY = new javax.swing.JLabel();
        okCountry = new javax.swing.JButton();
        okProvince = new javax.swing.JButton();
        okCanton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registro de Rescatista");
        jLabel1.setMaximumSize(new java.awt.Dimension(146, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(146, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(146, 16));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSurnameActionPerformed(evt);
            }
        });

        slider.setMaximum(2);

        jLabel3.setText("Correo / Usuario");

        jLabel4.setText("Contraseña");

        jLabel6.setText("País");

        LabelProvince.setText("Provincia");

        LabelCanton.setText("Cantón");

        LabelDistrict.setText("Distrito");

        labelFN.setText("Primer Nombre");

        labelSN.setText("Segundo Nombre");

        labelFS.setText("Primer Apellido");

        labelSS.setText("Segundo Apellido");

        tag1.setText("Hombre");

        tag2.setText("Mujer");

        tag3.setText("Otros");

        labelCed.setText("Cédula");

        LabelDate.setText("Fecha Nacimiento");

        jLabel5.setText("/");

        jLabel10.setText("/");

        LabelDD.setText("DD");

        LabelMM.setText("MM");

        LabelYY.setText("AA");

        okCountry.setText("OK");
        okCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCountryActionPerformed(evt);
            }
        });

        okProvince.setText("OK");
        okProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okProvinceActionPerformed(evt);
            }
        });

        okCanton.setText("OK");
        okCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCantonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDistrict)
                            .addComponent(jLabel6)
                            .addComponent(LabelProvince)
                            .addComponent(LabelCanton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(district, javax.swing.GroupLayout.Alignment.LEADING, 0, 115, Short.MAX_VALUE)
                                    .addComponent(canton, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(province, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(country, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(okCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(okProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(okCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFN)
                            .addComponent(labelSN)
                            .addComponent(labelFS)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(FSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(SName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(labelSS)
                            .addComponent(SSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelDate)
                        .addGap(137, 137, 137))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCed)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ced, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(tag1)
                                            .addGap(18, 18, 18)
                                            .addComponent(tag2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tag3))))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelMM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YY, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelYY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelFN))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(labelSN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelFS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(okCountry)))))
                    .addComponent(SName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelProvince)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okProvince))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tag1)
                    .addComponent(tag2)
                    .addComponent(tag3)
                    .addComponent(LabelCanton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelCed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okCanton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelDistrict)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelMM)
                            .addComponent(LabelYY)
                            .addComponent(LabelDD))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSurnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Validation.verifyPassword(passField.getPassword())){
        try {
            SysConexion con = new SysConexion();
            try (Connection connection = con.obtConexion()) {
                
                CallableStatement callableStatementIdProvince;
                callableStatementIdProvince = connection.prepareCall("{ ? = call getCantonID(?) }");
                callableStatementIdProvince.registerOutParameter(1, OracleTypes.NUMBER);
                callableStatementIdProvince.setString(2, (String) canton.getSelectedItem());
                callableStatementIdProvince.execute();
                int cantonId = callableStatementIdProvince.getInt(1);
                callableStatementIdProvince.close();
                
                
                CallableStatement callableStatement1 = connection.prepareCall("{ ? = call getDistrictID(?, ?) }");
                callableStatement1.registerOutParameter(1, OracleTypes.NUMBER);
                callableStatement1.setString(2, (String) district.getSelectedItem());
                callableStatement1.setInt(3, cantonId);
                callableStatement1.execute();
                int distId = callableStatement1.getInt(1);
                callableStatement1.close();
                
                
                CallableStatement callableStatement;
                callableStatement = connection.prepareCall("{call InsertPerson(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");
                callableStatement.setInt(1, distId);
                callableStatement.setString(2, fName.getText());
                callableStatement.setString(3, SName.getText());
                callableStatement.setString(4, FSurname.getText());
                callableStatement.setString(5, SSurname.getText());
                callableStatement.setInt(6, parseInt(ced.getText()));
                int var_year = parseInt(YY.getText()); // Año
                int var_month = parseInt(MM.getText());     // Mes 
                int var_day = parseInt(DD.getText());    // Día
                
                Calendar calendar = Calendar.getInstance();
                
                
                calendar.set(Calendar.YEAR, var_year);
                calendar.set(Calendar.MONTH, var_month);
                calendar.set(Calendar.DAY_OF_MONTH, var_day);

                java.util.Date userBirthday = calendar.getTime(); // Obtén la fecha
                java.sql.Date sqlUserBirthday = new java.sql.Date(userBirthday.getTime()); // Convierte a java.sql.Date

                callableStatement.setDate(7, sqlUserBirthday);
                char[] pass = passField.getPassword();
                String fullPassword = new String(pass);
                callableStatement.setString(8, fullPassword);
                callableStatement.setString(9, email.getText());
                callableStatement.setString(10, String.valueOf(slider.getValue()));
                callableStatement.execute();
                callableStatement.close();
                
                
                CallableStatement callableStatement2;
               callableStatement2 = connection.prepareCall("{call InsertRescuer(?)}");
                
                callableStatement2.setInt(1, Consult.getPersonId(parseInt(ced.getText())));
                
                callableStatement2.execute();
                callableStatement2.close();
                connection.close();
                JOptionPane.showMessageDialog(null, "Aceptado y guardado!"); 
            }  
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "error: " + e); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "error: La contraseña no cumple los requisitos!"); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void okCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCountryActionPerformed
        filling.FillProvince((String) country.getSelectedItem(), province);
        province.setVisible(true);  
        okProvince.setVisible(true);
        LabelProvince.setVisible(true);
    }//GEN-LAST:event_okCountryActionPerformed

    private void okProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okProvinceActionPerformed
        filling.FillCanton((String) province.getSelectedItem(), canton);
        canton.setVisible(true);
        okCanton.setVisible(true);
        LabelCanton.setVisible(true);
    }//GEN-LAST:event_okProvinceActionPerformed

    private void okCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCantonActionPerformed
        filling.FillDistrict((String) canton.getSelectedItem(), district);
        district.setVisible(true);
        LabelDistrict.setVisible(true);
    }//GEN-LAST:event_okCantonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterRescuer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterRescuer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterRescuer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterRescuer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterRescuer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DD;
    private javax.swing.JTextField FSurname;
    private javax.swing.JLabel LabelCanton;
    private javax.swing.JLabel LabelDD;
    private javax.swing.JLabel LabelDate;
    private javax.swing.JLabel LabelDistrict;
    private javax.swing.JLabel LabelMM;
    private javax.swing.JLabel LabelProvince;
    private javax.swing.JLabel LabelYY;
    private javax.swing.JTextField MM;
    private javax.swing.JTextField SName;
    private javax.swing.JTextField SSurname;
    private javax.swing.JTextField YY;
    private javax.swing.JComboBox<String> canton;
    private javax.swing.JTextField ced;
    private javax.swing.JComboBox<String> country;
    private javax.swing.JComboBox<String> district;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelCed;
    private javax.swing.JLabel labelFN;
    private javax.swing.JLabel labelFS;
    private javax.swing.JLabel labelSN;
    private javax.swing.JLabel labelSS;
    private javax.swing.JButton okCanton;
    private javax.swing.JButton okCountry;
    private javax.swing.JButton okProvince;
    private javax.swing.JPasswordField passField;
    private javax.swing.JComboBox<String> province;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel tag1;
    private javax.swing.JLabel tag2;
    private javax.swing.JLabel tag3;
    // End of variables declaration//GEN-END:variables
}
